markdown_extensions:
- sane_lists
- smarty
- toc:
    permalink: true
nav:
- Home:
  - The Bitflow Project: https://bitflow.readthedocs.io/en/latest/
  - Data Sources, Sinks and Format: https://bitflow.readthedocs.io/en/latest/data-format/
  - Bitflow Script: https://bitflow.readthedocs.io/projects/bitflow-antlr-grammars/en/latest/bitflow-script/
  - Naming Conventions: https://bitflow.readthedocs.io/en/latest/naming/
- Implementations:
  - go-bitflow: index.md
  - bitflow4j (Github): https://github.com/bitflow-stream/bitflow4j
  - python-bitflow: https://bitflow.readthedocs.io/projects/python-bitflow/en/latest/
- Related Projects:
  - bitflow-collector: https://bitflow.readthedocs.io/projects/go-bitflow-collector/en/latest/
  - bitflow-coordinator (Github): https://github.com/bitflow-stream/bitflow-coordinator
  - bitflow-process-agent (Github): https://github.com/bitflow-stream/bitflow-process-agent
plugins:
- search
repo_url: https://github.com/bitflow-stream/go-bitflow
site_author: Anton Gulenko
site_description: Go Bitflow Documentation
site_name: Go Bitflow
theme: readthedocs
